### ISSUE TITLE
Node version

### ISSUE THREAD

**Issue by salzhrani** [hapijs/nes#101]
Is it possible to require at least the LTS version (currently 4.3.2)? are there any issues with 4.x that we can help with?

**Comment by hueniverse** [comment]
I was just lazy making the tests run on both. They changed an error message in 5.x that breaks 4.x. It works just fine on 4.x.

**Comment by salzhrani** [comment]
Could you point which line has that issues? tests run fine on v4.0.0, v4.3.2 and v5.7.1 using nvm

**Comment by hueniverse** [comment]
https://travis-ci.org/hapijs/nes/builds

Look for failed tests.
