### ISSUE TITLE
Client.js getting root as undefined

### ISSUE THREAD

**Issue by neilmalgaonkar** [hapijs/nes#105]
Hi,

I am trying out with hapi nes protocol in my current project. for testing purpose I implemented first example given on github page.

I included client.js file into script tag in chat.html page from dist folder of nes. 
but when I try  new nes.Client() or new Nes.Client() I get nes/Nes is undefined error.

After adding some console.log in client.js I realised that root is "**undefined**" while passing to factory function.

following is the snippet of code generated by running command `npm run build-client`

```js
var _typeof = typeof Symbol === "function" && typeof Symbol.iterator === "symbol" ? function (obj) { return typeof obj; } : function (obj) { return obj && typeof Symbol === "function" && obj.constructor === Symbol ? "symbol" : typeof obj; };

(function (root, factory) {

    // $lab:coverage:off$

    if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object' && (typeof module === 'undefined' ? 'undefined' : _typeof(module)) === 'object') {
        module.exports = factory(); // Export if used as a module
    } else if (typeof define === 'function' && define.amd) {
            define(factory);
        } else if ((typeof exports === 'undefined' ? 'undefined' : _typeof(exports)) === 'object') {
            exports.nes = factory();
        } else {
            root.nes = factory();
        }

    // $lab:coverage:on$
})(**undefined**, function () {

// code related to client is here
});
```
If I update the code by removing **undefined** and replacing it with **window** code works perfectly.
I am not sure if its generated wrongly or I am missing something.
Please let me know If I done something wrong.

**Comment by hueniverse** [comment]
@tkh44 @kpdecker can you help?

**Comment by kpdecker** [comment]
@neilmalgaonkar this was a build problem. #108 should fix this.
