### ISSUE TITLE
Getting ECONNRESET when browser closed using subscriptions.

### ISSUE THREAD

**Issue by meenie** [hapijs/nes#110]
When setting up a subscription from the client to the server and then closing the browser tab, the following line shows up in the logs:

```
160411/144928.592, [log,connection,client,error], data: {"code":"ECONNRESET","errno":"ECONNRESET","syscall":"read"}
```

Should this be ignored? Or is this an issue?  It does call the `onUnsubscribe()` callback, so there are no issues cleaning up any lingering connections.

**Comment by hueniverse** [comment]
Usually this is not an issue. You should keep track to make sure you are not seeing an unusual number of these which may indicate a problem with loosing clients.
