### ISSUE TITLE
Scalable publish subscribe

### ISSUE THREAD

**Issue by mcollina** [hapijs/nes#111]
The current implementation of nes does not allow the publish / subscribe mechanism to scale beyond the single instance. I am the author of http://npm.im/mqemitter https://www.npmjs.com/package/mqemitter-redis and https://www.npmjs.com/package/mqemitter-mongodb, a family of library to support pub/sub in memory and on top of other brokers.

Would you accept a PR that replaces the current structure based on Call with MQEmitter?

**Comment by devinivy** [comment]
While I am very interested in scaling nes across multiple app servers, my impression is that there should be more flexible way to do this than replacing call with some other library.  I'd like to see nes provide some useful hooks that allow one to implement this on their own, or to see someone simply wrap nes.

**Comment by hueniverse** [comment]
I am not going to add any new external dependency for distributed pub/sub in nes. It is beyond the scope of this module and something that is trivial to implement outside of it. If you are going to use some distributed pub/sub infrastructure, all you need to do is insert it in between your call to publish something and nes' publish method.

I don't see how adding hooks or some kind of plugin infrastructure makes this better or how the current nes API prevents you from using any other pub/sub architecture with it.

**Comment by mcollina** [comment]
>  It is beyond the scope of this module and something that is trivial to implement outside of it.

What is trivial for someone is not trivial for another, and having dealt with pub/sub systems for a good chunk of the last 5 years, I tend to say that it is never trivial, and most projects do not get it right on the first go.

I think that the fact that this topic is not considered at all is a bit problematic. When adopting this technology, it is easy to get the question "does it scale through multiple nodes", and the answer is currently "there is no standard way or example to do so". Even though I prefer nes approach, socket.io addresses these concerns http://socket.io/docs/using-multiple-nodes/.

However you are right, looking through the API and the code, it is somewhat easy to add this feature, but how to do it is buried within the doc and definitely it is not immediate while skimming throughit. As far as I understood, I should hook to the broker subscription in the `onSubscribe` callback (https://github.com/hapijs/nes/blob/master/API.md#serversubscriptionpath-options), and when it receives a message from the parent broker, do `socket.publish()` (https://github.com/hapijs/nes/blob/master/API.md#socketpublishpath-message-callback). 

I would like to provide this functionality as a Hapi plugin on top of nes, should I wrap/overwrite `server.subscribe()` and `server.publish()`, or is there any hook for this?

**Comment by devinivy** [comment]
I would suggest implementing something with a different name, like `server.publishFarAndWide()`.

**Comment by mtharrison** [comment]
There is [`server.decorate()`](http://hapijs.com/api#serverdecoratetype-property-method-options) to safely extend the `server` object with new methods.

**Comment by hueniverse** [comment]
This brings up an interesting idea about letting one plugin override the decorations of another.

@mcollina if you start with a plugin that uses nes and adds new publish/subscribe methods, I'll get some new stuff into hapi that will allow you to publish it and override the built-in methods with new distributed versions.

**Comment by mcollina** [comment]
@hueniverse I'll do that next week. It will be the perfect solution for my problem.

**Comment by devinivy** [comment]
If you don't mind pinging here, I'd love to see what you come up with.  @hueniverse interesting feature idea– I certainly wouldn't complain!

**Comment by mcollina** [comment]
Here it is folks: https://github.com/mcollina/multines.

I went for `publishFar` and  `subscriptionFar`, but overriding `publish` and `subscription` would be fantastic to avoid issues.

Let me know what you think :).

cc @geek
