### ISSUE TITLE
Connect fails to check for previous internal socket when connecting.

### ISSUE THREAD

**Issue by tkh44** [hapijs/nes#125]
If you call connect() before calling disconnect the previous `this._ws` is not properly cleaned up.

You can see `this._ws` being set here with no check.
https://github.com/hapijs/nes/blob/3c2b81f0781a2044b5b7f6fddb5a6b8aa0be5fdb/lib/client.js#L176

**Comment by hueniverse** [comment]
This is marked as breaking change because it changes the internal timings of callbacks and notifications. You should test your application before upgrading to ensure you do not currently rely on specific timings (order of on___ events and function callbacks).
