### ISSUE TITLE
Support option to swap out ws with compatible package

### ISSUE THREAD

**Issue by mtharrison** [hapijs/nes#128]
Similar to the engine.io [`wsEngine` option](https://github.com/socketio/engine.io#methods-1) to use a compatible websocket package, such as [uWebSockets](https://github.com/alexhultman/uWebSockets).

**Comment by hueniverse** [comment]
This raises the question if we should pick a default engine to begin with?

**Comment by Miscellaneous** [comment]
uWebSockets above engine.io, but do the API's follow the elegance which makes Hapi? I really do appreciate Nes communication with JSON (very flexible), thou it toke me a while too understand, I didn't do a proper read on protocol...

**Comment by salzhrani** [comment]
[primus(]https://github.com/primus/primus) seems interesting but not sure if it fits.
