### ISSUE TITLE
client.js built already transpiled

### ISSUE THREAD

**Issue by afgallo** [hapijs/nes#130]
Is there any chance to get **/nes/lib/client.js** built and transpiled as a result of your build process?

ES2015 arrow functions (and other features) don't fit in with my current setup and workflow so when I run a build (which concatenates .js files and uglify them) I get an error because the source uses some ES2015 features.

Just to be clear, there is ***nothing*** wrong with the code or anything - it's just my setup that requires ES5 unfortunately.

**Comment by gergoerdosi** [comment]
Isn't that the case? https://github.com/hapijs/nes/blob/master/package.json#L42

**Comment by hueniverse** [comment]
https://github.com/hapijs/nes/blob/master/client.jshttps://github.com/hapijs/nes/blob/master/client.js
