### ISSUE TITLE
Client.WebSocket.OPEN is a callback.

### ISSUE THREAD

**Issue by damiandennis** [hapijs/nes#143]
This is probably an issue with angular2 and its zones library, but I will just start here as I could get this working using Websockets on its own (not using your library) and using your code on the server.
Currently trying to get the client side of websockets working inside an angular2 application however for some reason Client.WebSocket.OPEN is a callback not a number so I keep getting a disconnect error.

**Comment by hueniverse** [comment]
I have no idea. I don't use Angular. This code is working just fine for me.

**Comment by damiandennis** [comment]
Yeah I am pretty positive its an Angular2 issue, loading it via systemjs I have the issue but if I include it globally I dont have the issue, could possibly be a systemjs maybe but more likely angular.
