### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by gerenrot** [hapijs/nes#146]
Thanks for this package. It looks great!

I'd like to use it for 101 chat, more like real time messaging.
Will have ~1000 users with maybe 100 messages per second in peak time.
Will use cookie based authentication.

Should I use a subscribe path per user or have all users subscribe to the same path and use a subscription filter? It looks like either case will loop over all connections for each message sent to a client. This will become a performance issue and I would like to avoid it.

Please advise.

**Comment by hueniverse** [comment]
You need to figure out the idea mechanism to sort out who gets what message. Different paths is probably the most optimized but also the most restrictive.

**Comment by gerenrot** [comment]
I'll try different paths then. Thanks!
