### ISSUE TITLE
Send info within a for loop

### ISSUE THREAD

**Issue by vedran-maestral** [hapijs/nes#148]
I need to build a progress bar on the frontend. I am using React.js

```js
This is piece of code from the server:
`for (var i = 0; i < length; i++) {
    console.log("Preparing data: " + i + " of " + length )        
    request.server.publish('/progressbar', {
        message: i,
        type: 'success',
        params: "hello"
    }, {
        user: request.auth.credentials.id
    });

    matrix[i] = new Array(i)
    for (var j = 0; j < i; j++)
        matrix[i][j] = distance(input[i], input[j])
}
 return matrix`
```
Problem is with the first loop, it never sends the data to the front end.
Actually, this is two fold problem. If I have smaller amount of data (iterator less then 300), then the data is indeed sent, but once the proccess is done.

Another problem is, if I have over approximatelly 500 iterations, then it is never send at all.

If I send this alone:
` request.server.publish('/progressbar', {
        message: i,
        type: 'success',
        params: "hello"
    }, {
        user: request.auth.credentials.id
    });`

Then it works without problem.

**Comment by hueniverse** [comment]
Your for loop is blocking the main thread so nothing else can happen. You should read up about how node works and how to handle blocking operations. Instead of a for loop, you should use something like `async.eachSeries()` and add a `setImmediate()` in there to give other operations breathing room.
