### ISSUE TITLE
Trying to connect to Hapi Nes from C# websockets

### ISSUE THREAD

**Issue by Miscellaneous** [hapijs/nes#150]
C#:
` WebSocket w = new WebSocket( new Uri("ws://hapiserver.unknown:3333/socket") );
`

I'm getting this "error" from Hapi:
`{"statusCode":400,"payload":{"error":"Bad Request","message":"Cannot parse message"}}
`

Hapi:
```
server.register( Nes, function ( err ) {
    server.route({
        method: 'GET',
        path: '/socket',
        config: {
            id: 'hello',
            handler: function (request, reply) {
                return reply('world!');
            }
        }
    });
});
```

Same url, when used within HTML, provide correct result.

Does anyone have experience connecting from/to C# (websocket-sharp)?

**Comment by Marsup** [comment]
Stab in the dark: it's probably emitting ping frames because their client and server libraries are made to work together, nes doesn't understand that and kicks you out.

**Comment by Miscellaneous** [comment]
From my c# game, I can receive a "response" when using [hapi-plugin-websocket](https://www.npmjs.com/package/hapi-plugin-websocket) (full-featured exclusive WebSocket route), so I don't think websocket-sharp client and server libraries are intended to work together exclusively.

**Comment by Marsup** [comment]
Except nes is checking the messages it gets, it's not just some server ignoring what it doesn't recognize. Read the protocol docs to get a sense of what you'll have to implement in C#.

**Comment by Miscellaneous** [comment]
Thanks indeed
