### ISSUE TITLE
onError is called on successful connection

### ISSUE THREAD

**Issue by quirm** [hapijs/nes#152]
I have a following piece of code:

``` javascript
const options = {};
const client = new Nes.Client(`ws://${API_HOST}`);

client.connect(options);

client.onConnect = () => {
  console.log('[nes] connected');
};

client.onError = (err) => {
  console.log('[nes] error:', err);
};
```

I would expect that I can use `connect` without a callback because I'm handling connection state and error inside corresponding handlers.

Unexpected behaviour num. 1:
When I do it like that, onError will be called with empty `err` param because of missing `if (err) { ... }` at https://github.com/hapijs/nes/blob/master/lib/client.js#L191

Unexpected behaviour num. 2:
When I use `connect` without any param, I'll get an error because of undefined `options` param at https://github.com/hapijs/nes/blob/master/lib/client.js#L156

Please let me know if it's desired to use `client.connect()` without params and if so, I'll create a pull request.

**Comment by hueniverse** [comment]
Calling `connect()` without a callback is not supported.
