### ISSUE TITLE
Karma Tests Failing

### ISSUE THREAD

**Issue by Kimutaibryan** [hapijs/nes#153]
Am using karma to run my tests but including nes causes my tests to fail 
```PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  SyntaxError: Parse error
  at /home/werick/ng-amrs/bower_components/nes/lib/client.js:29```
The client works fine but the tests can't run.

**Comment by hueniverse** [comment]
No clue from this limited information but my guess it that you are using an incompatible JS version.

**Comment by Marsup** [comment]
Try using a non-outdated phantomjs.
