### ISSUE TITLE
client won't reconnect if the server is down when connect is called

### ISSUE THREAD

**Issue by paulovieira** [hapijs/nes#154]
Nes deals well with the following scenario:
- 1.1) server is initially online
- 1.2) client tries to connect (connection is established)
- 1.3) server goes offline (connection is dropped)
- 1.4) server goes online again (connection is re-established)

However if the server is initially offline, it doesn't seem be working. That is:
- 2.1) server is initially offline
- 2.2) client tries to connect (connection is not established)
- 2.3) server goes online (client won't try to reconnect)

Is this the expected behaviour or is it a bug? I played with the `timeout` option but the problem remains.

The problem seems to be in fact that `this._reconnect()` is not called in the `ws.onerror` callback (which is the callback that's executed in step 2.3 when the connection is not established).

On the other hand, looking at the `ws.onclose` callback (which is executed in step 1.4), we see that `this._reconnect()` is called there.

**Comment by paulovieira** [comment]
Meanwhile I found a similar issue at #149 , which gives a clear response. The second scenario is considered an error, and error should be handled by the user, not by nes.

**Comment by delia-m** [comment]
I have same issue with exactly same use-case.
I understand that I should handle error 
but auto reconnection onError is working in ios but not in android. 
Is this behaviour in android on purpose?

**Comment by hueniverse** [comment]
Seems to be working correctly. See new test.
