### ISSUE TITLE
Request: asynchronous onConnection/onDisconnection

### ISSUE THREAD

**Issue by andrezzoid** [hapijs/nes#158]
Would be great if plugin options `onConnection` and `onDisconnection` could have callbacks, for instance, if one needs to make a database read/write on each socket connection.

**Comment by mtharrison** [comment]
Those options already take a function.

> `onConnection` - a function with the signature `function(socket)` invoked for each incoming client connection where:
    - `socket` - the Socket object of the incoming connection.
`onDisconnection` - a function with the signature `function(socket)` invoked for each incoming client connection on disconnect where:
    - `socket` - the Socket object of the connection.

**Comment by andrezzoid** [comment]
I know that. I was suggesting they could have a callback, like `function(socket,  callback)` in case you needed to acess the DB or any other kind of long operation for each socket connection.

**Comment by hueniverse** [comment]
It should not matter if you need to make async calls because you are not returning a value here. It's not like if you delayed the callback from returning it will have any impact. This is an event, not an interaction.
