### ISSUE TITLE
Behaviour when subscribing to an unauthorised route after connect or before is different

### ISSUE THREAD

**Issue by cur3n4** [hapijs/nes#159]
Before a connection is made, if we subscribe to a number of routes and one them is unauthorised, when the connection is established the whole connection is finalised because of the one unauthorised route.
However when the connection is active, if we subscribe to an unauthorised route, that subscription is eliminated and the connection remains active.

https://github.com/hapijs/nes/blob/58cbf8941326c3d635022026cef4d0e43cb68f18/lib/client.js#L214-L220

vs

https://github.com/hapijs/nes/blob/58cbf8941326c3d635022026cef4d0e43cb68f18/lib/client.js#L526-L532

**Comment by hueniverse** [comment]
That's true for any errors subscribing as part of connecting or reconnecting. There is not much else we can do here.
