### ISSUE TITLE
client.message() function doesn't return the callback message

### ISSUE THREAD

**Issue by unutoiul** [hapijs/nes#161]
var client = new Nes.Client('ws://www.localhost:8000');
client.message(message, function(err, message){
     console.log('message', err);
     console.log('message', message);
 });

**Comment by hueniverse** [comment]
Huh?

**Comment by unutoiul** [comment]
Hi,

So when i'm sending a message to the server from frondend using the function 

client.message(message, function(err, message){

});

the callback function with the message argument is never returned...

any idea why?

**Comment by hueniverse** [comment]
What is the server doing with it? Are you handling it and returning a reply?

**Comment by unutoiul** [comment]
Yes you are right,  I didn't return anything on the server side...works fine.

Thanks,
Lucas
