### ISSUE TITLE
Client side repo, Nes and Peer dependencies. 

### ISSUE THREAD

**Issue by simonmcmanus** [hapijs/nes#163]
We are running our front and back end code in different repos, each with their own package.json file. 

This results in the front end code including Nes which has a peer dependency of Hapi which is not in the same repo. 

NPM install works with a warning but the npm shrinkwrap command errors. 
 
Is it possible to use npm shrinkwrap with Nes in a repo that does not include Hapi?

**Comment by hueniverse** [comment]
I am not thrilled about the idea of moving the client code to another repository. It's a pain to keep the two in sync when they are in different repos. I am not sure what's the right solution here is.

@othiym23 ?

**Comment by d3viant0ne** [comment]
@hueniverse - The approach repos like angular have taken may be applicable here. Core, router and so on reside in the same source repo & are published as a single version of independent libraries having their own package.json and so on.

It takes a bit of orchestration and scripting to handle the publishing efficiently but would provide a workable middle ground.

**Comment by hueniverse** [comment]
Going to close this for now. If this becomes an issue for more people I'll revisit.

**Comment by AugustinLF** [comment]
@hueniverse That would indeed be something I'd love, the warning is kind of annoying. Perhaps working with a monorepo (lerna for instance, should, if I'm right, solve this problem) would make this possible without making your life too complicated? 😄 

I admit not being really experienced about monorepos, but if you're interested, I can work on a PR to help you!

**Comment by hueniverse** [comment]
I don't really want to deal with it.

**Comment by AugustinLF** [comment]
I understand :) Anyway, if you change your mind, I'll make the PR, I'm now comfortable with Lerna and can help you with that!
