### ISSUE TITLE
nes + hapi-auth-jwt2 + dogwater

### ISSUE THREAD

**Issue by finedays** [hapijs/nes#164]
Hello guys, 

I have some troubles using NES with jwt authentication using Waterline/Dogwater.

here is my server.js:
```
'use strict'
const Hapi = require('hapi')
const Hoek = require('hoek')
const hapiAuthJWT = require('hapi-auth-jwt2')
const Dogwater = require('dogwater')
const sailsmysql = require('sails-mysql')
const Nes = require('nes')

// load models

const config = require('./configs/test_credentials')
const router = require('./routes/router').router
const validate = require('./lib/validate').validate

const server = new Hapi.Server()
server.connection({ port: 8000, routes: { cors: true } })

server.register(require('inert'), (err) => {
  Hoek.assert(!err, err)
})

server.register({
  register: Dogwater,
  options: {
    adapters: {
      dndDisk: sailsmysql
    },
    connections: {
      dndDB: .....................
    }
  }
}, (err) => {
  Hoek.assert(!err, err)
})

server.register(hapiAuthJWT, (err) => {
  Hoek.assert(!err, err)
})

server.auth.strategy('jwt', 'jwt',
  { key: config.jwtsecret,
    validateFunc: validate,
    verifyOptions: { ignoreExpiration: true },
    headerKey: 'authentication-token'
  })

server.register(Nes, (err) => {
  Hoek.assert(!err, err)
})

server.auth.default('jwt')

server.dogwater([ CreditCard, Passenger, FavoriteLocation, Trip, Driver, TripRoute, PaymentLog, Promotion, DriverRating, PassengerRating, Administrator, Country, CountryPrice, LatestDriverLocation, Language ])

server.route(router)

server.start((err) => {
  Hoek.assert(!err, err)
  console.log('Server started at:', server.info.uri)
})
```

My route for the socket is:
```
{
    method: 'GET',
    path: '/ws',
    config: {
      id: 'hello',
      auth: 'jwt',
      handler: function (request, reply) {

                return reply('world!');
            }
    }
  }
```

validate function is: 
```
function validate (decoded, request, callback) {
  const passenger = request.collections().passenger
  passenger.findOne(decoded.id)
    .then((passenger) => {
      if ((decoded.username) === (passenger.username)) {
        return callback(null, true)
      } else {
        return callback(null, false)
      }
    })
}
```

and client is: 
```
var Nes = require('nes')
var client = new Nes.Client('ws://localhost:8000')

client.connect({auth: {headers: {'Authentication-Token': 'token'}}}, (err) => {
  if (err) return console.log(err)
  client.request('hello', (err, payload) => {
    if (err) return console.log('err is ' + err)
    console.log(payload)
  })
})
```

when I run the client, using valid token (I am testing it with other routes) it gives the following error:

> { Error: An internal server error occurred
    at new NesError (/Users/vgenev/Projects/dnd-server/node_modules/nes/lib/client.js:77:19)
    at parse (/Users/vgenev/Projects/dnd-server/node_modules/nes/lib/client.js:616:25)
    at parse (/Users/vgenev/Projects/dnd-server/node_modules/nes/lib/client.js:48:16)
    at Client._onMessage (/Users/vgenev/Projects/dnd-server/node_modules/nes/lib/client.js:603:9)
    at WebSocket.ws.onmessage (/Users/vgenev/Projects/dnd-server/node_modules/nes/lib/client.js:261:25)
    at WebSocket.onMessage (/Users/vgenev/Projects/dnd-server/node_modules/ws/lib/WebSocket.js:442:14)
    at emitTwo (events.js:106:13)
    at WebSocket.emit (events.js:191:7)
    at Receiver.ontext (/Users/vgenev/Projects/dnd-server/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/vgenev/Projects/dnd-server/node_modules/ws/lib/Receiver.js:536:18
  type: 'server',
  statusCode: 401,
  data:
   { error: 'Unauthorized',
     message: 'An internal server error occurred' },
  headers: undefined,
  path: undefined }

and the server error is:

> Debug: internal, implementation, error 
    TypeError: Cannot read property 'findOne' of undefined
    at Object.validate [as validateFunc] (/Users/vgenev/Projects/dnd-server/lib/validate.js:4:12)
    at /Users/vgenev/Projects/dnd-server/node_modules/hapi-auth-jwt2/lib/index.js:87:23
    at /Users/vgenev/Projects/dnd-server/node_modules/jsonwebtoken/verify.js:27:18
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)

What I have seen is that actually the passenger is not created by: `  const passenger = request.collections().passenger` in the validate function, although the token is correctly decoded.

Can you help me deal with this situation?

**Comment by devinivy** [comment]
This is probably a dogwater usage question rather than a nes issue.  Feel free to open an issue on the dogwater repo.  One thing I can add is that dogwater is careful to sandbox access to models within plugins that define those models.  The way to get around that (as needed) is to call `request.collections(true).passenger`.  You might also ensure that `passenger` is the exact model identity set on the model definition.

**Comment by finedays** [comment]
Thanks, that `request.collections(true).passanger` did it!
I will post it in the dogwater repo, though.
