### ISSUE TITLE
Nested `credentials` when making requests with Nes Client

### ISSUE THREAD

**Issue by albatrocity** [hapijs/nes#176]
* Hapi `16.1.1`
* Nes `6.4.2`

When making requests over HTTP, the `request.auth` object looks like this from a route handler:

```js
{ isAuthenticated: true,
 credentials: 
  { name: 'ross',
    id: '58ebbefbd4f24441716b2164',
    provider: 'guest' },
 artifacts: 
  { name: 'ross',
    id: '58ebbefbd4f24441716b2164',
    provider: 'guest' },
 strategy: 'userCookie',
 mode: 'required',
 error: null }
```

However, when making the same request at the same endpoint, the `request.auth` object looks like this (`credentials` inside `credentials`):

```js
{ isAuthenticated: true,
 credentials: 
  { credentials: 
     { name: 'ross',
       id: '58ebbefbd4f24441716b2164',
       provider: 'guest' },
    artifacts: 
     { name: 'ross',
       id: '58ebbefbd4f24441716b2164',
       provider: 'guest' } },
 artifacts: null,
 strategy: 'bypass',
 mode: 'required',
 error: null }
```

I'm currently using the `token` auth type, authorizing like this from the client:

```js
fetch('/nes/auth', {credentials: 'include'})
    .then(res => res.json())
    .then((res) => {
      wsClient.connect({ auth: res.token }, err => {
        if (err) { throw err }
        // do the stuff, works just fine
      })
    })
```

My default auth strategy is an implementation of [hapi-auth-cookie](https://github.com/hapijs/hapi-auth-cookie)

If I register a test authentication strategy, the same thing happens:

```js
    // auth plugin
    server.auth.scheme('bogus', (server, options) => {
      return {
        authenticate(request, reply) {
          reply.continue({ credentials: { id: 1 } })
        }
      }
    })
    server.auth.strategy('fake', 'bogus')

    // nes plugin config
    auth: {
      type: 'token',
      route: 'fake',
    }
```

Same result for `request.auth` and `request.socket.auth`.

Is this intentional or is it an implementation error? I'd like to be able to access the credentials at the same path regardless of the method used to make the request.

**Comment by iagomr** [comment]
Same thing for me, I am not really able to make the server.publish filter per user because it is supposed to match credentials.user instead of credentials.credentials.user. Or am I missing something?

**Comment by iagomr** [comment]
I made a quick fix on my case. I'm sure this is not correct, but I am not aware of the inner workings of your library so I tried not to break anything. On your file index.js, line 193:

`                const credentials = {
                    credentials: request.auth.credentials,
                    user: request.auth.credentials.user,
                    artifacts: request.auth.artifacts
                };
`

**Comment by hueniverse** [comment]
I am happy to look at a self contained test showing this problem. I don't have time to debug this and I don't have the same issue in my code.

**Comment by albatrocity** [comment]
@hueniverse apologies for the delay on this. Here's [an example repo](https://github.com/albatrocity/nes-credentials-example) demonstrating the issue

**Comment by mtharrison** [comment]
Confirmed this is a bug and still present in master and latest release. PR coming shortly.

**Comment by mtharrison** [comment]
Thanks for the example repo btw, that made debugging it way easier.
