### ISSUE TITLE
Nes client in Angular 2

### ISSUE THREAD

**Issue by hanct** [hapijs/nes#178]
Hi,

Is it possible to use Nes in client side using angular 2 and typescript? Any sample code for this.

Regards,

**Comment by sfabriece** [comment]
@hanct , sis you ever find the answer to this?

**Comment by hanct** [comment]
Hi sfabriece,

I manage to find an answer to this, but after a while,  i no longer using Nes any longer cos of my project requirement. But luckily, I did not remove the code , and merely comment them out in my source code, so i still have it, So here it is:

The below are codes of typescript for angular 2/4. Hope it helps

import * as Nes from 'nes'

constructor(){ 
        this.client = new Nes.Client('ws://127.0.0.1:7777');
        this.client.connect((err) =>{
          //whatever you want to do
        })
    }

sendMessageToBackEnd(){
                  this.client.request({path:'login', method:'POST',payload:{loginInfo:$event}}, (err, payload)=> {   
                              console.log(payload.response)//print out response from remote server
                          
            });
