### ISSUE TITLE
Using custom authentication strategies like in hapi

### ISSUE THREAD

**Issue by chamini2** [hapijs/nes#180]
I wanted to use a `jwt` strategy like we already do in Hapi, but found that setting

```
server.subscribe('/path', {
  auth: 'jwt'
});
```

does not work, how can I achieve this?

**Comment by hueniverse** [comment]
You still protect the actual endpoint with JWT, but you use one of the options nes supports for the protocol level. nes uses its own method to authenticate you to the nes websocket connection, and from there it uses normal auth. Just look at the tests for examples.
