### ISSUE TITLE
hapi aborting streams doesn't play well with nes

### ISSUE THREAD

**Issue by Marsup** [hapijs/nes#184]
New hapi behavior introduced in https://github.com/hapijs/hapi/commit/38f7d47de959747f23abbacaf2f34eefeecf0be1 doesn't seem to be dealt with correctly by nes, it transmits this kind of payload on failure :
```json
{
    "type": "request",
    "id": 20,
    "statusCode": 200,
    "payload": {
        "statusCode": 500,
        "error": "Internal Server Error",
        "message": "An internal server error occurred"
    }
}
```

**Comment by hueniverse** [comment]
Bug in hapi.
