### ISSUE TITLE
Issue with node 8.2.0

### ISSUE THREAD

**Issue by aldrakos** [hapijs/nes#186]
I am using nes 6.4.3 on a hapijs 16.5.0 server. 
On the client side (seperate app), I am using AureliaJS with nes 6.4.3, of which I import only nes/client and use in a websocket service. Up till upgrading to node 8 (having used node 6 and node 7 versions) everything worked ok.

After upgrading to node 8, things start up ok (node app starts just fine), but when the CLIENT runs and the code reaches the init part: ``` ws = new Nes.Client(...) ); ws.connect({...});``` the node server crashes with error :
```
C:\Program Files\nodejs\node.exe: c:\ws\src\env-inl.h:131: Assertion `(trigger_id) >= (0)' failed.
```

On the client side, there are two things that happen: 
First, the ws.onDisconnect() event is fired with willReconnect false and  log:
```
code: 1006
explanation: "Abnormal closure"
reason: ""
wasClean: false
wasRequested: false
willReconnect: false
```

Then, the error is thrown from the ws.connect() function: 
```Error: Request failed - server disconnected```

There are no errors (not related to WS) and everything works ok if I do not init/connect the WebSockets. Everything else works as intended.

Any ideas why this happens? Is anyone else experiencing this issue?
Is this a node 8 error? Should it be reported on the node github?

**Comment by Marsup** [comment]
Many libraries crashed on 8.2.0, try 8.2.1.

**Comment by aldrakos** [comment]
Seems I jumped the gun. It is indeed fine with 8.2.1. Thanks!
