### ISSUE TITLE
Error: reply interface called twice

### ISSUE THREAD

**Issue by hanct** [hapijs/nes#188]
Hi, 

i am currently using nes and hapijs.
I have setup my client and server code similar to this github example under Route invocation heading.
When my server (hapijs) execute reply(..) more than once, i got error from hapi.js "The error is Error: reply interface called twice"

In my understanding, I thought websocket connection should allow server-side to initiate sending message to client side as many times as we want?  Or does nes only allow server side to reply only once per incoming request from client?

**Comment by Marsup** [comment]
That's https://github.com/hapijs/nes#subscriptions in the docs.
