### ISSUE TITLE
Non-started server holds process open

### ISSUE THREAD

**Issue by alanshaw** [hapijs/nes#190]
If I create a new Hapi server my process exits, unless I call `server.start()`.

If I create a Hapi server with Nes, my process doesn't exit until I call `server.stop()` (even though the server is not started)

e.g.

**process exit ok**
```js
const Hapi = require('hapi')
const Good = require('good')
const server = new Hapi.Server()

server.connection({ port: 3000 })

server.register([
  Good
], (err) => {
  if (err) throw err
  console.log('Server ready, not started...')
  // process now exits
})
```

**process does not exit**
```js
const Hapi = require('hapi')
const Nes = require('nes')
const Good = require('good')
const server = new Hapi.Server()

server.connection({ port: 3000 })

server.register([
  Nes,
  Good
], (err) => {
  if (err) throw err
  console.log('Server ready, not started...')
  // process does not exit
  // server.stop() <- I have to call this to exit the process
})
```

The reason I'm reporting this is because I have existing tests and am using `server.inject`, so I never call `server.start`. I added `Nes` to the project and the tests no longer exit when complete.

**Comment by mtharrison** [comment]
I think this is because a timer is started for hearbeats even before the server starts listening. I too would not expect it to prevent process exiting. I'll investigate if it's viable to delay that timer until startup.

**Comment by alanshaw** [comment]
Thank you @mtharrison 😄
