### ISSUE TITLE
Is there a way to suppress error messages in the logs when a client disconnects?

### ISSUE THREAD

**Issue by nfriend** [hapijs/nes#192]
When a client disconnects, I get this error message in my Hapi server's console:

```powershell
170928/120436.817, [log,connection,client,error] message: read ECONNRESET, stack: Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
[2017-09-28 09:04:36.819] [ERROR] console - Debug: connection, client, error
    Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TCP.onread (net.js:569:26)
```

Is there a way to suppress these messages?  I took a look through the documentation and the existing issues on this repository but couldn't find an obvious solution.

**Comment by ambrons** [comment]
@nfriend is this specific to NES? or are you talking in terms of hapi in general?  I'm seeing quite a few of these messages in Hapi's server logs, but it has nothing to do with NES or websockets.

**Comment by nfriend** [comment]
@ambrons - Yes, this is specific to NES.  The error message gets printed when the browser ends the Websocket connection to the Hapi server (for example, when the tab is closed).

**Comment by JKHeadley** [comment]
I'm experiencing this as well. Does anyone know an easy way to at least catch and handle the error?

**Comment by JKHeadley** [comment]
Looks like this is a result of a recent change in the ws module:

https://github.com/websockets/ws/issues/1256

Still not sure how to add a handler to catch the error though.
