### ISSUE TITLE
version 7 Not Working on Windows 10 installed 6^ and issue resolved.

### ISSUE THREAD

**Issue by jberall** [hapijs/nes#197]
I am running windows 10 PRO.
I upgraded from 6.4.3 to 7 and I got the following.
When I reinstalled with 6.4.3 the server started.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@5.5.1
3 info using node@v8.3.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle hapi-nes@1.0.0~prestart: hapi-nes@1.0.0
6 info lifecycle hapi-nes@1.0.0~start: hapi-nes@1.0.0
7 verbose lifecycle hapi-nes@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle hapi-nes@1.0.0~start: PATH: C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin;C:\xampp\htdocs\angular4\hapi\socket\hapi-nes\node_modules\.bin;C:\Program Files\Docker\Docker\Resources\bin;C:\Program Files\Broadcom\Broadcom 802.11 Network Adapter;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\Program Files\PostgreSQL\pg96\bin;C:\xampp\php;C:\ProgramData\ComposerSetup\bin;C:\Program Files\PuTTY\;C:\xampp\htdocs\angular4\hapi\phantomjs-2.1.1-windows\bin;C:\Program Files\nodejs\;C:\Program Files\Redis\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Users\Owner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\AppData\Roaming\Composer\vendor\bin;C:\Users\Owner\AppData\Local\atom\bin;C:\Users\Owner\AppData\Local\Microsoft\WindowsApps;C:\Users\Owner\AppData\Roaming\npm;C:\Program Files\Microsoft VS Code\bin
9 verbose lifecycle hapi-nes@1.0.0~start: CWD: C:\xampp\htdocs\angular4\hapi\socket\hapi-nes
10 silly lifecycle hapi-nes@1.0.0~start: Args: [ '/d /s /c', 'node start.js' ]
11 silly lifecycle hapi-nes@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle hapi-nes@1.0.0~start: Failed to exec start script
13 verbose stack Error: hapi-nes@1.0.0 start: `node start.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at EventEmitter.emit (events.js:213:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Owner\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:125:13)
13 verbose stack     at ChildProcess.emit (events.js:213:7)
13 verbose stack     at maybeClose (internal/child_process.js:927:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid hapi-nes@1.0.0
15 verbose cwd C:\xampp\htdocs\angular4\hapi\socket\hapi-nes
16 verbose Windows_NT 10.0.15063
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Owner\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v8.3.0
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error hapi-nes@1.0.0 start: `node start.js`
22 error Exit status 1
23 error Failed at the hapi-nes@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Marsup** [comment]
v7 is only for hapi v17, did you upgrade ?

**Comment by jberall** [comment]
No I'm running "hapi": "^16.6.2",
When I ran the command npm i -S hapi@latest I still get version 16.  
Thanks for the prompt reply.
Is their any observable clients for Nes?

**Comment by Marsup** [comment]
v17 is still in RC, you have to be explicit about installing it.

**Comment by Marsup** [comment]
Observability can probably be added by any observable framework you're using.
