### ISSUE TITLE
issues when using Docker

### ISSUE THREAD

**Issue by Banjerr** [hapijs/nes#199]
Hello,

I am experiencing some trouble when using Nes with Docker. 

I have a server running Alpine with Node installed. Port 9000 is open and mapped to port 80 on my host machine. I'm also using React and RethinkDB, and the routes i've set up with Hapi work, with the exception of the subscription. I can hit a route within React and it will pull all entries from RethinkDB, I can hit a route with a POST and add a new entry, but the websocket never seems to connect. And eventually will throw..

`Error in connection establishment: net::ERR_CONNECTION_TIMED_OUT`

Has anyone successfully used Nes within Docker yet?

Relevant code:

server
```  
App.subscription('/complaints/updates');

  App.start(err => {
    if (err) {
      throw err
    }

    //Setup the RethinkDB change-feed and push it to the websocket connection.
    App.methods.db.setupChangefeedPush();

    console.log(`Server running at ${App.info.uri}`)
  });
```

database
```
server.method('db.setupChangefeedPush', () => {
    r.db(db).table(code_snippets).changes().run(conn, (err, cursor) => {
      cursor.each((err, item) => {
        console.log('db item is ', item);
        server.publish('/complaints/updates', item.new_val);
      });
    });
  }, {
    callback: false
  });
```
the console.log runs here, as I see "db item is .." in the terminal, but then it seems to get lost and client never connects

and front-end
```
this.client = new nes.Client('ws://172.18.0.1:9000');
this.client.connect(function (err) {
      if (err) {
        console.log(err);
        return false;
      }

     var handler = function (item) {
       console.log('item is ', item);
       App.appendComplaint(item);
     };

     console.log('connected');
     this.client.subscribe('/', handler, function (err) {console.log('err is ', err);});
    });
```

**Comment by hueniverse** [comment]
Anything running between the client and server? nginx? AWS LB? anything at all?

**Comment by Banjerr** [comment]
Nope, no Apache/nginx so far. Just running Docker locally. The app container is just alpine with Node installed. 

Sent from my iPhone

**Comment by cjihrig** [comment]
You have `this.client = new nes.Client('ws://172.18.0.1:9000');` in your front end code. You mentioned that 9000 was exposed from the container as port 80 on your local machine. Could the IP and port used by nes on the client be the problem?

**Comment by Banjerr** [comment]
@cjihrig you hit the nail on the head; as soon as I read your comment it started to make sense. The client connection needed to be `new nes.Client('ws://localhost:80');`

closing this ticket! thanks everyone!
