### ISSUE TITLE
server disconnected using example code

### ISSUE THREAD

**Issue by JKHeadley** [hapijs/nes#205]
- hapi v16.1.0
- nes v6.5.1

Hello, I'm trying to run the first example code from the readme but when my client tries to connect I get an error: `Failed to send message - server disconnected`.  I'm trying to run the client on the browser.  When I run the client in node it works fine.

Here's the code I'm using:

`server`
```javascript
var Hapi = require('hapi');
var Nes = require('nes');

var server = new Hapi.Server();
server.connection({ port: 8126 });

server.register(Nes, function (err) {
  console.log("ERROR:", err)

  server.route({
    method: 'GET',
    path: '/h',
    config: {
      id: 'hello',
      handler: function (request, reply) {
        return reply('world!');
      }
    }
  });

  server.start(function (err) {
    console.log("ERROR:", err)
  });
});
```

`client-browser`
```javascript
    let Nes = require('nes')
    let client = new Nes.Client('ws://localhost:8126')
    client.connect((err) => {
      if (err) {
        console.error("ERR:", err)
      } else {
        client.request('hello', (err, payload) => {   // Can also request '/h'
          if (err) {
            console.log("ERR:", err)
          }

          console.log("CHAT:", payload)
        })
      }
    })
```

I'm sure this is a simple problem but I can't seem to get around it.  Any help would be greatly appreciated.

**Comment by hueniverse** [comment]
I don't have the time to help but will leave this open in case someone else can take a look.

**Comment by JKHeadley** [comment]
@hueniverse update, commenting out the if statement here:
       https://github.com/hapijs/nes/blob/237328303bb449d75b21b7ad099f8173c57af77c/lib/client.js#L413

seems to have fixed my issue.  My value of `this._ws.readyState` is `1`, and apparently not equal to the value of `Client.WebSocket.OPEN`.  Do you know what might be going on here?
