### ISSUE TITLE
Access to remote address in onSubscribe and onUnsubscribe

### ISSUE THREAD

**Issue by salehe** [hapijs/nes#209]
It is useful to have some information about the connection in these functions.

It seems that access to connection information via socket parameter was introduced in https://github.com/hapijs/nes/commit/71e9232bb84ad30ab0a5f62647b07144d44e2930 , but was later removed.

**Comment by mtharrison** [comment]
Perhaps a `socket.info` object would be useful, similar to hapi's `request.info`.
