### ISSUE TITLE
A few typos in the API docs

### ISSUE THREAD

**Issue by newswim** [hapijs/nes#213]
I think several of the link problems came from the `await` keyword being added to the `client.connect()` section. Several places are still linking to the previous heading for part of the docs. Correct link is now:

https://github.com/hapijs/nes/blob/master/API.md#await-clientconnectoptions

There's also another place where a markdown link isn't being correctly terminated.

---

<img width="808" alt="screen shot 2018-02-04 at 12 11 58 am" src="https://user-images.githubusercontent.com/6667096/35774798-195c1aa6-0940-11e8-876d-4fa609f8d677.png">

---

I'd be happy to fix these, just thought it best to open up an issue first. Much thanks to the maintainers
 🙏

**Comment by cjihrig** [comment]
Pull requests fixing broken markdown are always welcome 😄

**Comment by mtharrison** [comment]
👍
