### ISSUE TITLE
Help need. Best way how to publish user's online status 

### ISSUE THREAD

**Issue by kyvour** [hapijs/nes#218]
I'm working on the chat app which will contain different rooms and each room will contain different topics.
Each room has manager (authenticated user) and any number anonymous users (i.e. visitors).
Each topic in the room implemented as separate NES (v6.5.1) subscription, i.e. client subscribes to the path `/chat/:roomId/:topicId`

But I need to create additional NES subscriptions which will sent user online status, for example
`/chat/:roomId/manager` or `/chat/:roomId/visitor`. These subscriptions should send online status of manager/visitor for the given room.
When visitor open room page, the frontend app will be subscribed to `/chat/:roomId/manager` subscription and visitor will be able to see if manager is online or not.

The main problem for me is decide when server can get online status for user and publish it to subscription.

I think that I can use `onMessage` method on plugin registration. As I think, in this method I will be able check if message is a heartbeat message (has `ping` type) and send online status via `server.publish()`

But I feel that this is not so fine solution and it can be implemented in some another way.

Is there any best way or some recommendations how I can do this?

**Comment by mtharrison** [comment]
> The main problem for me is decide when server can get online status for user and publish it to subscription.

You can use `onConnection`/`onDisconnection` plugin options to track user presence and publish that information however you choose on your configured subscriptions.

**Comment by kyvour** [comment]
Thanks for the reply.
Will be `onDisconnection` method invoked, when user closes browser tab or heartbeat request fails?

How I can handle a case when server crashes for some reason (and all users should be shown `offline`)? Can I use `client.onError` in this case ?

**Comment by mtharrison** [comment]
> Will be onDisconnection method invoked, when user closes browser tab or heartbeat request fails?
Yes, in both cases. 

> How I can handle a case when server crashes for some reason (and all users should be shown offline)? Can I use client.onError in this case ?
For the client side? Take a look at client API here: https://github.com/hapijs/nes/blob/master/API.md#client. You probably want `onDisconnect` on the client side too.
