### ISSUE TITLE
AJAX libraries like Nes and Axios won't import from node_modules directory

### ISSUE THREAD

**Issue by SamuelEarl** [hapijs/nes#227]
Since this issue involves Nes, I assume that this would be the place to report this bug. If not please let me know where I should post this issue.

It appears that hapi.js is not importing AJAX libraries from the node_modules directory into any front-end JavaScript modules. I keep getting this error:

`Uncaught ReferenceError: Nes is not defined`

I have had this problem with both Nes and Axios. I was only able to get them to work through a CDN script tag. I have NOT had any problems importing Nes or Axios into any backend JavaScript files. I have also been able to import other non-AJAX libraries into my front-end and backend JavaScript modules without any problems. So I am guessing that this is a problem with AJAX libraries being imported into front-end modules only. 

These are the versions that I have installed:
hapi: 17.2.0
nes: 7.0.2

These are the different import statements that I have tried:

`import Nes from 'nes/client';`
`import Nes from 'nes';`
`var Nes = require('nes/client');`
`var Nes = require('nes');`

Thank you for your help!

**Comment by mtharrison** [comment]
I'm not sure I understand this issue but I don't do a lot of front end stuff. Are you using webpack?

**Comment by SamuelEarl** [comment]
Thank you for your quick response, @mtharrison.

I tried something else that is now working. If I change the import to this:

`import nes from 'nes/client';` (notice the lowercase nes)

...and change any references to `nes` to match the lowercase name, then the import works. I have switched back and forth between uppercase and lowercase and even tried it in Chrome and Firefox to see if my app was possibly caching the CDN import. After deleting the CDN import and changing the import to lowercase, everything works. When I switch back to uppercase, it breaks.

Any ideas? This is very strange. Since I have been able to fix this issue with lowercase naming, this issue is not critical. However, it would be nice to figure out what is going on.

Thank you for your help! (I love your book, by the way.)

-----

I am using a Browserify plugin with Gulp to handle my "bare" import specifiers from node_modules and to bundle my front-end modules. I was thinking about switching to webpack, though. Do you think webpack might handle things differently?

Here is some more info that might be helpful:

I am using Handlebars v4.0.11. My layout file looks like this right now:

```
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>App Title</title>
  <link rel="stylesheet" href="{{ path.css }}main.min.css">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto+Slab|Source+Code+Pro" rel="stylesheet">
  <link rel="shortcut icon" type="image/png" href="{{ path.images }}favicon.png?v=0" sizes="16x16 32x32 64x64">
</head>

<body>
  <div class="container">
    {{{ content }}}
  </div>
  <script src="https://use.fontawesome.com/470271407b.js"></script>
  <script src="{{ path.js }}lib.js"></script>
  <script src="{{ path.js }}app.js"></script>
  <script src="{{ path.js }}views.js"></script>
</body>
</html>
```
I am importing all of my scripts into 1 of 3 files and Browserify converts each file into a separate bundle:
* lib.js: The entrypoint file for external libraries (e.g. jQuery, D3.js, Axios).
* app.js: The entrypoint file for general application code (e.g. form handling, logging in/out, navigation, file upload handlers).
* views.js: The entry point file for page-specific code (e.g. frontpage carousel, news comments system).

_NOTE: The `{{ path.js }}` syntax comes from the `hapi-named-routes` package._

Since I am importing Nes into my lib.js file, here is what that file looks like right now:

```
import 'babel-polyfill';
import Chart from 'chart.js';
import nes from 'nes/client';
```

Any thoughts as to why lowercase imports are working, but uppercase imports are not would be greatly appreciated.

Thank you!

**Comment by mtharrison** [comment]
I'm going to mark this as `help wanted` as I don't have any experience with browserify. If I were in your situation though I would try to make an example that is as small as possible. I.e. just a file that imports nes and does something with it and try to run that through browserify and see if you get the same problem. If you do get the same problem then share that example and you'll be able to get help debugging it a lot easier. If the problem has gone away then the issue is somewhere else in your code.

**Comment by SamuelEarl** [comment]
Good suggestion. I will do that. Thank you!

**Comment by SamuelEarl** [comment]
I found what the problem was a while back, but forgot to update this post. I can't remember what the fix was, but I think it was simply a typo in a file somewhere that was overriding my imports and messing things up for me.
