### ISSUE TITLE
Hapi17 Nes plugin client-side onDisconnect event not functioning like example?

### ISSUE THREAD

**Issue by BPatrick92** [hapijs/nes#231]
I am trying to build a custom safe disconnection module for the client, in-order for me to do so I came to the conclusion that I needed to know when the server died/went offline. Looking at the Hapi documentation:
[here](https://github.com/hapijs/nes/blob/master/API.md#clientondisconnect ) this task seemed trivial to accomplish. However, upon testing, it seemed as if the onDisconnect event doesn't catch all disconnection types. 

If the client calls client.disconnect() directly, the onDisconnect event fires, however, if the server abruptly stops/dies, the onDisconnect isn't called, rather, the onError even is called. Am I doing something wrong?

Current setup

Server:

```

const Hapi = require('hapi');
const Nes = require('nes');

const server = new Hapi.server({
  host: "127.0.0.1",
  port: 8080
});


const start = async() => {

  await server.register(
  {
    plugin: Nes,
    options: {
      onConnection: (socket)=>{
        console.log("New connection");
      }
    }
  });

  await server.start();
  console.log("Server up:",server.info.uri);
}

start();
```

Client:

```
const Nes = require('nes');
const client = new Nes.Client('ws://localhost:8080');

async function start(){
try{
  await client.connect({
    retries: 1
  });

client.onError = (err) =>{
  console.log("I get the error here:", err);
}

client.onDisconnect = (willReconnect, log)=>{
  console.log("This is never called!");
}

}catch(err){
console.log("Reporting this error", err);
}

};

start();
```

**Comment by mtharrison** [comment]
What version of nes are you using. When running your example and stopping the server it logs:

```
console.log("This is never called!");
```

**Comment by BPatrick92** [comment]
I am using Nes@7.0.2, I have since upgraded to Nes8.0.0 - I am not sure if I should mark this issue as resolve since although this is a bug in version 7 of Nes, it is no longer in the latest version.
