### ISSUE TITLE
Subscriptions are not cleaned on client disconnect

### ISSUE THREAD

**Issue by kpdecker** [hapijs/nes#24]
It does not look like subscriptions are being cleaned when the client disconnects, leaving the possibility of leaking.

With this diff, this test will now fail as the subscribers object has length of 2, maintaining a reference to the disconnected client.

```
diff --git a/test/client.js b/test/client.js
index a61a833..e19c6df 100755
--- a/test/client.js
+++ b/test/client.js
@@ -748,6 +748,10 @@ describe('Browser', function () {
                                     client2.disconnect();
                                     setTimeout(function () {
 
+                                        var listener = server.connections[0].plugins.nes._listener;
+                                        var match = listener._router.route('sub', '/');
+                                        expect(match.route.subscribers.length).to.equal(1);
+
                                         server.publish('/', 'heya');
                                     }, 10);
                                 }, 10);
```

**Comment by hueniverse** [comment]
Yeah, I put a temporary hack in there to drop the dead ones on publish() but it needs to move to the disconnection flow.

**Comment by hueniverse** [comment]
I've decided that it is better to keep an array of strings (socket ids) instead of having to manage the subscription lists when sockets disconnect. This way they will get cleaned at little cost on publish.

**Comment by hueniverse** [comment]
Ok. Not it's fixed properly.
