### ISSUE TITLE
Nes won't try to reconnect on a websocket error

### ISSUE THREAD

**Issue by mtharrison** [hapijs/nes#242]
When `onerror` is called on the client Websocket object we do not try to reconnect. This seems like an oversight. We try to reconnect if the connection goes away in other cases but not on error.

**Comment by mtharrison** [comment]
Out of curiosity I checked socket.io's behaviour in the same situation and it will attempt to reconnect.

**Comment by hueniverse** [comment]
Sounds like an oversight.

**Comment by mtharrison** [comment]
Closed #247
