### ISSUE TITLE
eachSocket behaves as synchronous without filter, but async with filter

### ISSUE THREAD

**Issue by p16** [hapijs/nes#248]
Hi there,
when using the subscription filter I think the `eachSocket` function behaves as async instead of synchronous.

[`route.subscribers._forEachSubscriber`](https://github.com/hapijs/nes/blob/6b9ed164237dee8c4e754339e8b303997b06fe73/lib/listener.js#L411) is used in `eachSocket` but its [definition makes it an `async` function](https://github.com/hapijs/nes/blob/6b9ed164237dee8c4e754339e8b303997b06fe73/lib/listener.js#L603).

I'm open to work on a fix on this, but I'm not sure how to proceed given the `each` function passed to `_forEachSubscriber` sometimes is [synchronous](https://github.com/hapijs/nes/blob/6b9ed164237dee8c4e754339e8b303997b06fe73/lib/listener.js#L386) and sometimes is [async](https://github.com/hapijs/nes/blob/6b9ed164237dee8c4e754339e8b303997b06fe73/lib/listener.js#L290).

Do you have any idea?

**Comment by mtharrison** [comment]
Good spot. As we accept an async `each()` we probably need to return `Promise`s  from the functions that call that and document appropriately.

**Comment by hueniverse** [comment]
The resolution is to move the entire interface to async. In most cases this would not be a breaking change, but some operations (as seen in the test) would now require an `await` next to `eachSocket()`.
