### ISSUE TITLE
Client Doesn't Work With Node?

### ISSUE THREAD

**Issue by framerate** [hapijs/nes#258]
Reading through docs and issues it would seem that the client is browser/node compatible, but

https://github.com/hapijs/nes/blob/819b6c402ed416de318e46f7845bee78c6b488e2/lib/client.js#L139

That line implies that when used with Node there is no WebSocket implementation?

Output when trying some of the simplest examples from the ReadMe:
```
(node:14692) UnhandledPromiseRejectionWarning: TypeError: h.WebSocket is not a constructor
    at h._connect (/home/justin/code/doomtrooper/dt-ai-agent/node_modules/nes/dist/client.js:1:2415)
```

I tried polyfilling a websocket lib (ws) to nes.Client.Websocket but then I just get "socket error".

I couldn't find anything in the docs or the issue tracker. I'm assuming all the users are using browser/electron (like I normally am). Is it possible to use this with Node?

Any help is appreciated and I can PR an update to the README after I figure it out. Thanks!

**Comment by hueniverse** [comment]
Should work just fine.

See: https://github.com/hapijs/nes/blob/master/lib/index.js#L134

and the tests in test/client.js

**Comment by framerate** [comment]
Thanks @hueniverse. I'll assume maybe it's a dependency or even local env problem and I'll investigate further. Examples are definitely failing for me tonight.
