### ISSUE TITLE
Can't resolve '@hapi/nes/client'

### ISSUE THREAD

**Issue by genediazjr** [hapijs/nes#280]
I'm using webpack and have upgraded to using the new `@hapi` directive
This works
```
const client = require('nes/client');
```
This can't resolve '@hapi/nes/client'
```
const client = require('@hapi/nes/client');
```

**Comment by dominykas** [comment]
Can you try `require('@hapi/nes/lib/client');`?

**Comment by dominykas** [comment]
I can see the docs need an update (or actual `client` exposed).

**Comment by genediazjr** [comment]
@dominykas I get
```Unexpected token: punc «)» ```

**Comment by hueniverse** [comment]
@genediazjr you will need to configure your webpack setup to properly convert the client code to whatever JS version you support.
