### ISSUE TITLE
Error: Connection requires authentication

### ISSUE THREAD

**Issue by kirbyjs** [hapijs/nes#297]
#### Support plan

* *which support plan is this issue covered by?* (e.g. Community, Core, Plus, or Enterprise): Community
* *is this issue currently blocking your project?* (yes/no): yes
* *is this issue affecting a production system?* (yes/no): no

#### Context

* *node version*: 10.17.0
* *module version with issue*: 11.2.2
* *last module version without issue*: N/A (tried down to 10.0.0)
* *environment* (e.g. node, browser, native): node, browser
* *used with* (e.g. hapi application, another framework, standalone, ...): hapi application
* *any other relevant information*:

#### What are you trying to achieve or the steps to reproduce?

Currently, I'm trying to add a pub/sub with `@hapi/nes` with cookie authentication. In production my app is using `@hapi/hapi` and `@hapi/cookie` to authenticate our REST endpoints.

This is the server code that I added:
``` js

server.register({
    plugin: Nes.plugin,
    options: {
        auth: {
            type: 'cookie',
            isSecure: config.isSecure,
            isSameSite: 'Lax'
        }
    }
});
server.subscription('/some-subscribe-endpoint');
await server.start();
```

This is the browser client code that I added:
``` js
import Nes from '@hapi/nes/lib/client';

const {host, protocol} = window.location;
const connectionUrl = (protocol === 'https:') ? `wss://${host}/` : `ws://${host}/`;
const client = new Nes.Client(connectionUrl);

fetch('/nes/auth', {credentials: 'same-origin'})
    .then(() => client.connect({delay: 2000, retries: 3}))
    .then(() => {
        client.subscribe(`/some-subscribe-endpoint`, (data) => {
            // do something
        });
    });
```

The `nes/auth` endpoint returns `{"status":"authenticated"}`, but I did see that the returned cookie size was massive:

![image](https://user-images.githubusercontent.com/13893942/70096431-af8dea80-15ec-11ea-83d5-9b3d2c028af7.png)

I'm not sure if that has anything to do with it or not. I also played around with the `password`, but that didn't really affect the size of the cookie. 

I also tested in Chrome, Firefox and Safari, and all of them had the same result.

#### What was the result you got?
`Error: Connection requires authentication`

#### What result did you expect?
No authentication issue.

**Comment by hueniverse** [comment]
Unfortunately, no community resources were available to help resolve this issue after two weeks, and it is being closed. We close unresolved community issues to keep the issue tracker organized and effective. Please check https://hapi.dev/support for other support options.
