### ISSUE TITLE
How will adding additional functionality work?

### ISSUE THREAD

**Issue by devinivy** [hapijs/nes#3]
I'm curious if there are any plans for allowing users to add additional functionality to the library.  For example, the [primus](https://github.com/primus/primus) project has a simple plugin system to modify and addend the simple API that it exposes.  We use this to implement "rooms" and clustering across multiple app servers.  It also allows addendums to the browser-facing library.  I'm curious what type of pattern would be encouraged to solve similar problems.

**Comment by hueniverse** [comment]
Probably not. Not trying to compete with all the other fully featured projects out there. This is aiming to allow you to make HTTP requests over WS to existing hapi routes, with all the security and request lifecycle baked in.
