### ISSUE TITLE
Nes most likely breaking in Node 22

### ISSUE THREAD

**Issue by damusix** [hapijs/nes#331]
### Runtime

NodeJS

### Runtime version

22

### Module version

13

### Last module version without issue

N/A

### Any other relevant information

Seems like there were breaking changes in Node22 that are making many of the Nes tests fail. 

### What are you trying to achieve or the steps to reproduce?

Run Nes tests in Node 22

### What was the result you got?

- authentication cookie *: Connection requires authentication
- Client defaults options.ws.maxPayload to zero (node): Expected undefined to equal specified value: { maxPayload: 0 }
- Listener accepts known origin: Connection terminated while waiting to connect

### What result did you expect?

Tests to pass

**Comment by Marsup** [comment]
I'm going to close this as CI with node 22 seems to be passing right now. Let me know if there are still stuff to fix related to this issue.
