### ISSUE TITLE
Strategies for sharing authentication between http routes and nes routes

### ISSUE THREAD

**Issue by salzhrani** [hapijs/nes#49]
What is the recommended approach for sharing authentication between hapi and hapi+nes? if for example hapi-auth-cookie is used on one server and certain parts of the app need access to `nes` on another server with a different subdomain ( or domain ).

**Comment by hueniverse** [comment]
There is no recommended approach. You should think about the nes channel as just another endpoint and configure authentication for it the way you would any other HTTP endpoint.
