### ISSUE TITLE
Unknown response type: response

### ISSUE THREAD

**Issue by UnwrittenFun** [hapijs/nes#50]
I have the following client code to be run in the browser using browserify.
```javascript
var client = new Nes.Client(url);
client.connect(function () {
  client.request("/test", function (err, res) {
    console.log(err, res);
  });
});
```

However, when I run this code, I get an `Uncaught TypeError: Illegal invocation` fired at line 504 in client.js (nes).
This line is:
```javascript
return self.onError(new Error('Received unknown response type: ' + update.type));
```

Not entirely sure what is going on there, but I added a `console.log` of the `update.type` just above that line and it returns `response`.

If i change line 483 in the same file from `if (update.type === 'request') {` to `if (update.type === 'response') {` the error goes away, and everything works as expected.

I have tried this using node v0.12.7 and v4.1.0 both server and client, reinstalling all node modules each time I switched but no luck. I am testing this in Google Chrome 46.0.2490.22

As a fix for now I am just changing the line as above, an actual fix would appreciated if possible, or tell me I am doing it wrong.

**Comment by hueniverse** [comment]
What version of nes are you using? the `'response'` type has been replaced and I can't find it in the code anymore.

**Comment by UnwrittenFun** [comment]
1.0.0

**Comment by hueniverse** [comment]
Can you scan your local copy of nes to see if you can find the `'response'` string anywhere? I don't see it on master. It used to be in the code before but it's not there anymore so it sounds like some old code left behind.

**Comment by UnwrittenFun** [comment]
Okay, something weird happened here then, fresh download today on the server from npm, yet I have just checked the version now and it is 0.3.0..
