### ISSUE TITLE
NES client required?

### ISSUE THREAD

**Issue by jamesdixon** [hapijs/nes#58]
A potentially stupid question: does NES require the use of the NES client specifically or can any WS-compatible client be used? I only ask because I'm using Ember on the front-end and there is already a solid "emberized" client called [ember-websockets](https://github.com/thoov/ember-websockets) that I was considering using. 

Thanks as always for the great work.

**Comment by hueniverse** [comment]
nes has it's own wire protocol on top of WS. You can implement it yourself, but you need something that understands the protocol.
