### ISSUE TITLE
Add message metadata for publish

### ISSUE THREAD

**Issue by kpdecker** [hapijs/nes#63]
Add the ability to include metadata to a particular message that is passed to the `filter` method, but is not sent to the final consumer.

This may be used, for example, to prevent sending a message to the session that generated the message in the first place.

**Comment by kpdecker** [comment]
Strawman:

```
server.publish(path, message, {metadata});
filter(path, message, {credentials, params, metadata}, next)
```

**Comment by hueniverse** [comment]
Seems ok. Why not call it options?

**Comment by kpdecker** [comment]
Was trying to leave room for other functionality in the future, for `publish`, this is actually an `options` argument with a `metadata` field.

**Comment by hueniverse** [comment]
I don't like the name metadata. How about `internal`?

**Comment by kpdecker** [comment]
Sure.
