### ISSUE TITLE
Minified cdn version is incorrect

### ISSUE THREAD

**Issue by geek** [hapijs/nes#73]
https://cdnjs.cloudflare.com/ajax/libs/nes/1.2.0/client.min.js 

vs.

https://cdnjs.cloudflare.com/ajax/libs/nes/1.2.0/client.js

**Comment by kpdecker** [comment]
This is picking up the es6 code not the es5 artifact. Who setup the
cloudflare hosting?

**Comment by hueniverse** [comment]
Not me.

**Comment by hueniverse** [comment]
Is there a way for me to fix this?

**Comment by geek** [comment]
not sure :/

**Comment by hueniverse** [comment]
Oh well.
