### ISSUE TITLE
Trying to get auth working with nes and hapi-auth-cookie

### ISSUE THREAD

**Issue by poeticninja** [hapijs/nes#75]
I am using hapi-auth-cookie for a `/login` route that sets a user session and a secondary `/test` for testing if the auth works. In the browser when I go to the `/test` route after I login the `request.auth.credentials` are available. But if I try to use nes to access the `/test` route the `request.auth.credentials` are null. I can't seem to figure out how to get nes to work the same way as the rest of my auth.

#### Login route:
``` js
server.route({
    method: 'POST',
    path: '/login',
    config: {
        handler: function(request, reply){

            var user = { id: 1, name: 'john'}; // some user from the database 

            request.auth.session.set(user);
            return reply(user);

        }
    }
});
```

#### Test route:
``` js

server.route({
    method: 'GET',
    path: '/test',
    config: {
        auth: {
            mode: 'try',
            strategy: 'basic'
        },
        handler: function (request, reply) {
            console.log('request.auth');
            console.log(request.auth);

            return reply('test');
        }
    }
});
```
#### Browser client nes:
``` js
client.request('/test', function (err, payload) {
    // payload -> 'hello!'
});
```

Thanks!

**Comment by hueniverse** [comment]
What do you pass to `client.connect()`?

**Comment by poeticninja** [comment]
Here is the `client.connect`:

``` js 
client.connect(function (err) {

    client.request('/test', function (err, payload) {
        // payload -> 'hello!'
    });
    
});
```

**Comment by hueniverse** [comment]
You need to make sure the browser is already logged in before connecting if you want to use direct auth mode.

**Comment by poeticninja** [comment]
I have tested connecting after the user is logged in and I have tested refreshing the browser for a fresh connection after being logged in. Both result in the credentials being null.

**Comment by hueniverse** [comment]
Can you post a full example that reproduces this?

**Comment by poeticninja** [comment]
Okay, I put something together real quick to see what I am working with. https://github.com/poeticninja/hapi-auth-nes-test

If you run with npm start and go to localhost:3000 you can see in the browser console a few things happening. First there is a POST request logging in the user, then an HTTP GET request is sent to `/test` and you can see in the node console log that the auth has credentials, then a websocket connection is established with a request to `test` using sockets and in the node console you will see that the request has no credentials.

I hope this helps. Let me know if you have questions.

**Comment by bsapot** [comment]
@poeticninja did you figure this out? I was having the same issue and found a resolution. If you configure nes for cookie authentication as follows: 
`options: {auth: {
            type: "cookie",
            isSecure: false
        }}
`
Authenticate as you normally would with your /login route. 
Then do a GET on /nes/auth - this will generate the NES cookie
Then call client.connect .. then your requests. 

I can provide a more detailed example if you are interested.

**Comment by kelkes** [comment]
I've already configured hapijs to use hapi-auth-cookie. Altough the cookie is send along the websocket request i still get a NesError with Unauthorized. Any Ideas?

**Comment by hueniverse** [comment]
@kelkes don't mix the two. Your auth cookie from hapi-auth-cookie needs to make it into the socket connection somehow. Your options are to grab it on the client side and manually generate a cookie header and pass it into the client.connect() method (direct auth), or to use the other methods where you will first need to make an http call to the nes special auth endpoint which will either return a token you can use with client.connect(), or will set another nes cookie for it.

**Comment by kelkes** [comment]
I see! Thanks for the hint.

**Comment by hueniverse** [comment]
The auth tests are a good place to start to see how the three auth modes work.

**Comment by kelkes** [comment]
My fault. I thought it will reuse the hapi auth config. I will have a look at the tests. :)

**Comment by kelkes** [comment]
I still do not get it... :(

I've set auth mode to direct. The cookie (set by regular login) is send with the Websockets Request (also tried sending it manually with the connect call).
Shouldn't it be piped into the default hapi auth strategy for validation? Still says auth missing.

**Comment by hueniverse** [comment]
You can't use the normal cookie flow to authenticate the ws request because we don't have access to the full request object as required by the hapi auth scheme. We just can't get into that code with the connection message we get from the ws upgrade request.

Direct mode means you are passing the required cookie in the connect() auth option directly. In the other two methods, you make an additional HTTP request to get back either a cookie or a token. If you get a token, you pass that in the connect() auth option. If you get a cookie, you just make the connect() call and the cookie set by the special nes endpoint takes care of it.

For example, using cookie more, you first make this HTTP call:
https://github.com/hapijs/nes/blob/master/test/auth.js#L57
Then you can make the connect request. In this test, the cookie header is passed in the ws client because it's not a browser but the browser will do it for you.

I don't have any free time to help beyond this.

**Comment by kelkes** [comment]
Thanks. Thats more than i hoped for. :)

**Comment by kelkes** [comment]
Just for the records. Using Nes.Client like

const client = new Nes.Client('http://localhost:' + server.info.port, { ws: { headers: { cookie: 'nes=' + cookie[1] } } });

Results in:
Uncaught SyntaxError: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.

Using Chrome Version 50.0.2661.94 (64-bit) on OSX 10.11.4

**Comment by kelkes** [comment]
Finally ;) Kudos to @hueniverse for all the help. It works.

**Comment by illustratordavid** [comment]
Hi @kelkes I'm having struggle with authenticating a cookie based connection myself.  Just wondered if you would be able to show me your final working lines creating new Nes.client and using the connect() function please? 

Thanks David

**Comment by kelkes** [comment]
@illustratordavid sure. if created a gist with some more or less pseudo code to showcase how i managed to get cookie-auth and nes working.

https://gist.github.com/kelkes/30eec9bf98d03235d38f327b6b66518f

Hope you find that helpful. Do not hesitate to ask if something is not clear enough.

**Comment by illustratordavid** [comment]
Brilliant! @kelkes thank you for taking the time to share your code, real help

**Comment by shengtaoli** [comment]
@kelkes  @illustratordavid  @hueniverse I have a similar but more complicated case. the question can be found here. https://stackoverflow.com/questions/44427198/can-someone-provide-an-solid-working-example-of-http-cookie-auth-that-involves-h

Basically I am authenticate user in via google auth using the hapi `bell` plugin. once authenticated i open a session and store a cookie to user. (up to this part it works fine). 

what i totally have no idea/ am lost is that how I can configure the Nes plugin to authenticate into websocket????? 

Here's the code, just in case:

index.js is :

```
const Hapi = require('hapi');
const Hoek = require('hoek');
const Bell = require('bell');
const Nes = require('nes');
const Inert = require('inert');
const path = require('path');
const Cookie = require('hapi-auth-cookie');
const dotenv = require('dotenv').config();


// Starting a Hapi server simply requires
// an instance of Hapi.Server. We leave it
// bare or we can add some configuration
const server = new Hapi.Server({
  connections: {
    routes: {
      files: {
        relativeTo: path.join(__dirname, 'public')
      }
    }
  }
});


// We need to specify a connection, which
// we can default to the port specified in
// an ENV variable, or 3001 if none is set.
// We also need to configure CORS for requests
// coming from a single page app
server.connection({ 
  host: 'localhost', 
  port: 50001,
  routes: {
    cors: {
      origin: ['*']
    }
  }
});

let ness = {
  register: Nes,
  options: {
    auth: {
      type: 'cookie',
      cookie: 'ws-auth',
      ttl: 24 * 60 * 60 * 1000,
      isSecure: process.env.NODE_ENV !== 'development',
      isHttpOnly: false,
    },
  }
};

server.register([Bell, Cookie, Inert, ness], function (err) {

  Hoek.assert(!err, err);
  server.route({
    method: 'GET',
    path: '/public/{param*}',
    handler: {
      directory: {
        path: '.',
        redirectToSlash: true,
        index: true
      }
    }
  });

  server.auth.strategy('google', 'bell', {
      provider: 'google',
      password: 'cookie_encryption_password_secure',
      isSecure: false,
      clientId: process.env.GOOGLE_CLIENT_ID,
      clientSecret: process.env.GOOGLE_CLIENT_SECRET,
      location: server.info.uri
  });

  server.auth.strategy('session', 'cookie', {
    password: process.env.SESSION_COOKIEOPTIONS_PASSWORD,
    cookie: 'sid',
    redirectTo: '/login',
    redirectOnTry: false,
    isSecure: false
  })

  server.subscription('/item');

  server.route(require('./lib/auth.js'));

  server.start((err) => {
    Hoek.assert(!err, err);
    console.log('Server started at:', server.info.uri);

    setInterval(function(){
      server.publish('/item', { id: 5, status: 'complete', value: Math.round(Math.random()*100) });
    }, 1000)

  });
});
```
I have a lib/auth.js file like such:

```
module.exports = [
  {
    method: '*',
    path: '/login',
    config: {
      auth: 'google',
      handler: function (request, reply)  {
        if (!request.auth.isAuthenticated) {
          return reply('Authentication failed due to: ' + request.auth.error.message);
        }
        let profile = request.auth.credentials;
        request.cookieAuth.clear();
        request.cookieAuth.set(profile);
        return reply.redirect('/public');
        //reply('<pre>' + JSON.stringify(request.auth.credentials, null, 4) + '</pre>');
      }
    }
  }
];
```
