### ISSUE TITLE
Possible to subscribe, unsubscribe, and resubscribe? v1.2.0

### ISSUE THREAD

**Issue by padmaia** [hapijs/nes#79]
When I try to subscribe, unsubscribe, and then resubscribe I am getting the error 'Client already subscribed'.  When I try subscribing twice to the same path with same socket I just end up getting the data twice.

Here is a code example:
```
subscribe(id) {
    clientSocket.subscribe(`/conversations/${id}`, (err, msg) => {
        if (msg) // dispatch action
        if (err) console.error(err);
    });
}

unsubscribe(id) {
    clientSocket.unsubscribe(`/conversations/${id}`);
}
```
*Both methods live in the same file.  The socket client is initiated in another module and required into this one.  

When I peek into clientSocket.subscriptions(), it has the path before I unsubscribe and is empty after I unsubscribe.  Is this expected behavior?

**Comment by hueniverse** [comment]
Can you confirm 1.2.1 fixes your issue?

**Comment by padmaia** [comment]
Yes, that seems to have resolved the issue. Thanks!
