### ISSUE TITLE
Question: Using Nes in a custom plugin with Glue

### ISSUE THREAD

**Issue by ambrons** [hapijs/nes#80]
I'm attempting to use Nes inside of my own plugin for managing websocket communication.  My existing app is using `rejoice` and `glue` with a manifest to configure and invoke hapi.  Based on the API documentation and the examples it doesn't appear that this is possible.

Thinking outside the box it might be possible to call `server.register` inside my plugin and internally register `nes`, but if that even works I don't think it's very clean.  What I was hoping for was an interface similar to `h2o2` where there's an object added to the route config of `server.route(...)` that could be used to pass all of this configuration for a specific plugin.

See the code below for an example of what I was thinking.

```javascript
'use strict';

const internals = {};


exports.register = (server, options, next) => {

    server.dependency('nes', internals.after.bind(null, options));

    return next();
};


internals.after = (options, server, next) => {

    server.route({
        method: 'GET',
        path: '/vote',
        config: {
            nes: {
                onMessage: internals.onMessage,
                heartbeat: {
                    interval: 20000,
                    timeout: 2000
                }
            },
            description: 'vote plugin',
            handler: internals.handler
        }
    });

    return next();
};


internals.onMessage = (socket, message, next) => {

    // implementation
    next();
}


internals.handler = (request, reply) => {

    return reply('world');
};


exports.register.attributes = {
    name: 'vote',
    version: '1.0.0'
};
```

**Comment by hueniverse** [comment]
I'm not following the issue here.

**Comment by ambrons** [comment]
Unless I'm missing something there's no way to config the Nes plugin sort of inside a `start.js` script or invoke it inside my plugins `register` method where I can set the various options of the Nes plugin that expect functions for a value.

My above example is a suggestion for adding a namespace to the config object of server.route() to allow the above.  Or am I missing something fundamental with Hapi that makes this already available.

**Comment by hueniverse** [comment]
Glue is limited to JSON settings. If you need to load nes via glue, you need to wrap it in another plugin that takes care of the function options.

**Comment by devinivy** [comment]
I assume you mean to say that rejoice is limited to JSON settings.  As of rejoice v2.1 (https://github.com/hapijs/rejoice/issues/25) this is no longer the case– you can also use a standard module.

**Comment by ambrons** [comment]
@hueniverse yeah that was the point I was making and I went that direction.  Sorry I should have closed this a while back.

**Comment by cameronbourgeois** [comment]
@ambrons did you ever get this working? I am using Glue `4.2.0` and Nes `6.5.1`.

I can't get the `onConnection` function to fire. I've tried including the package in my main manifest. And now I am trying to wrap it up in another package like this:

```
const Nes = require('nes');

exports.register = function registerCacheBuster(server, options, next) {
    server.register({
        register: Nes,
        options: {
            onConnection: function(socket) {
                socket.send({ status: 'CONNECTED' });
            }
        }
    });
    return next();
};

exports.register.attributes = {
    name: 'socketTest',
    version: '1.0.0'
};
```

All I want to do is send a message when a new client connects... and nothing really seems to work.
