### ISSUE TITLE
Question around handling constant data flow

### ISSUE THREAD

**Issue by mcdonnelldean** [hapijs/nes#82]
First off, great lib. Very easy to integrate and use. I have a question on best practice when pumping data to a subscription.

I have have a script that pulls data out of a db on 5 second intervals. Right now I am publishing this data to a subscription which I then subscribe to via a web app.

My question, is it ok to just pump data to publish regardless of whose listening or will I eventually kill the server if nobody pulls the data down. The data sets aren't huge (+-20 rows per tick) but are constant.

Should I be perhaps listening for subscribers so that I can tap and untap the feed to the db?

**Comment by hueniverse** [comment]
Nothing is being queued. If you publish and no one is subscribed it will just get gc'ed.

**Comment by mcdonnelldean** [comment]
Awesome!

Thanks for the quick response.

Kindest Regards,

Dean
