### ISSUE TITLE
Example from readme does not working

### ISSUE THREAD

**Issue by jt3k** [hapijs/nes#91]
I want to make a Websocket server but I discovered a problem.

![not working](https://i.imgur.com/AE8EDgs.png)

after connecting to the server I see ping, then I see the disconnect.

If I try to send message from browser in the response is returned this.

```
{"statusCode":400,"payload":{"error":"Bad Request","message":"Cannot parse message"}}
```

what am I doing wrong?

**Comment by hueniverse** [comment]
I have no idea. I need a code example to reproduce the issue.

**Comment by damiandennis** [comment]
yeah its weird getting the same issue. isn't that a code sample in the image?

**Comment by damiandennis** [comment]
ok I see why, need to pass a json string with specific criteria.

**Comment by jt3k** [comment]
how json-string will work?

**Comment by damiandennis** [comment]
Better to use the included clientside library as there are a few.

**Comment by jt3k** [comment]
I got rid of the idea to use hapi+nes as websoket server.

Better to use `nodejs-websocket`.
With this package my client code works well!
